#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define DEFINE_INSTRUCTION(name, args) {name, args}

#include <global.h>

enum {
	T_EOF,
	
	// Symbols
	T_ADD,
	T_SUB,
	T_MUL,
	T_DIV,
	T_COMMA,
	T_DOT,
	T_COLON,
	T_DIRECTIVE,
	
	// Complex
	T_INT,
	T_STRING,
	T_INSTRUCTION,
};

struct instruction {
	char* name;
	int argc;
};

struct label {
	char* name;
	uint32_t address;
	struct label* local_labels;

	struct label* next;
};

struct token {
	int type;
	int value;
	uint8_t* extra_bytes;

	struct token* next;
};

enum {
	I_NOP_INSTRUCTION,
	I_MOV_INSTRUCTION,
	I_ADD_INSTRUCTION,
	I_SUB_INSTRUCTION,
	I_MUL_INSTRUCTION,
	I_DIV_INSTRUCTION,
	I_OR_INSTRUCTION,
	I_XOR_INSTRUCTION,
	I_AND_INSTRUCTION,
	I_NOT_INSTRUCTION,
	I_INT_INSTRUCTION,
	I_SIVTE_INSTRUCTION,
	I_RIVTE_INSTRUCTION,
	I_IRET_INSTRUCTION,
	I_CMP_INSTRUCTION,
	I_JMP_INSTRUCTION,
	I_CALL_INSTRUCTION,
	I_RET_INSTRUCTION,
	I_JE_INSTRUCTION,
	I_JNE_INSTRUCTION,
	I_JG_INSTRUCTION,
	I_JGE_INSTRUCTION,
	I_JL_INSTRUCTION,
	I_JLE_INSTRUCTION,
	I_JC_INSTRUCTION,
	I_JNC_INSTRUCTION,
	I_JZ_INSTRUCTION,
	I_JNZ_INSTRUCTION,
	I_PUSH_INSTRUCTION,
	I_POP_INSTRUCTION,
	I_DB_INSTRUCTION,
	I_DS_INSTRUCTION
};

static const struct instruction ISA[] = {
	[I_NOP_INSTRUCTION] = DEFINE_INSTRUCTION("NOP", 0),
	[I_MOV_INSTRUCTION] = DEFINE_INSTRUCTION("MOV", 2),
	[I_ADD_INSTRUCTION] = DEFINE_INSTRUCTION("ADD", 2),
	[I_SUB_INSTRUCTION] = DEFINE_INSTRUCTION("SUB", 2),
	[I_MUL_INSTRUCTION] = DEFINE_INSTRUCTION("MUL", 2),
	[I_DIV_INSTRUCTION] = DEFINE_INSTRUCTION("DIV", 2),
	[I_OR_INSTRUCTION] = DEFINE_INSTRUCTION("OR", 2),
	[I_XOR_INSTRUCTION] = DEFINE_INSTRUCTION("XOR", 2),
	[I_AND_INSTRUCTION] = DEFINE_INSTRUCTION("AND", 2),
	[I_NOT_INSTRUCTION] = DEFINE_INSTRUCTION("NOT", 1),
	[I_INT_INSTRUCTION] = DEFINE_INSTRUCTION("INT", 1),
	[I_SIVTE_INSTRUCTION] = DEFINE_INSTRUCTION("SIVTE", 2),
	[I_RIVTE_INSTRUCTION] = DEFINE_INSTRUCTION("RIVTE", 1),
	[I_IRET_INSTRUCTION] = DEFINE_INSTRUCTION("IRET", 0),
	[I_CMP_INSTRUCTION] = DEFINE_INSTRUCTION("CMP", 2),
	[I_JMP_INSTRUCTION] = DEFINE_INSTRUCTION("JMP", 1),
	[I_CALL_INSTRUCTION] = DEFINE_INSTRUCTION("CALL", 1),
	[I_RET_INSTRUCTION] = DEFINE_INSTRUCTION("RET", 0),
	[I_JE_INSTRUCTION] = DEFINE_INSTRUCTION("JE", 1),
	[I_JNE_INSTRUCTION] = DEFINE_INSTRUCTION("JNE", 1),
	[I_JG_INSTRUCTION] = DEFINE_INSTRUCTION("JG", 1),
	[I_JGE_INSTRUCTION] = DEFINE_INSTRUCTION("JGE", 1),
	[I_JL_INSTRUCTION] = DEFINE_INSTRUCTION("JL", 1),
	[I_JLE_INSTRUCTION] = DEFINE_INSTRUCTION("JLE", 1),
	[I_JC_INSTRUCTION] = DEFINE_INSTRUCTION("JC", 1),
	[I_JNC_INSTRUCTION] = DEFINE_INSTRUCTION("JNC", 1),
	[I_JZ_INSTRUCTION] = DEFINE_INSTRUCTION("JZ", 1),
	[I_JNZ_INSTRUCTION] = DEFINE_INSTRUCTION("JNZ", 1),
	[I_PUSH_INSTRUCTION] = DEFINE_INSTRUCTION("PUSH", 1),
	[I_POP_INSTRUCTION] = DEFINE_INSTRUCTION("POP", 1),
	[I_DB_INSTRUCTION] = DEFINE_INSTRUCTION("DB", 3),
	[I_DS_INSTRUCTION] = DEFINE_INSTRUCTION("DS", 3)
};

#endif